### ISSUE TITLE
modify and select the attributes I want to train

### ISSUE THREAD

**Issue by kclch** [dangweili/pedestrian-attribute-recognition-pytorch#6]
I want to select some properties in the attribute dataset for training and testing. How do I modify and select the attributes I need to train in train.prototxt and deploy.prototxt? thank you very much

**Comment by YL-123** [comment]
I modified dataset['selected_attribute'] = range(35) to dataset['selected_attribute'] = (0,1,2,3,80) and generated new peta_dataset.pkl, i added --num_att=5 \ in train.sh, but in training,  the num_att is 35 instead of 5. I tried modified selected_attribute str in original PETA.mat but with no success, is anything I missed here since I wanted to train the 5 age attributes? thank you very much!

**Comment by YL-123** [comment]
sorry for reopening this, wanted to update that I solved the issue, thanks again!

**Comment by nanhui69** [comment]
> sorry for reopening this, wanted to update that I solved the issue, thanks again!

how do you adreess it ?
